# -*- coding: utf-8 -*-
__author__ = 'neo'

IOT_EVENT = 20000

# TCPINTF
IOT_TCPINTF_EVENT = (IOT_EVENT + 500)

IOT_PF_TO_TCPINTF_REQ = (IOT_TCPINTF_EVENT + 1)
IOT_PF_TO_TCPINTF_RSP = (IOT_TCPINTF_EVENT + 2)
IOT_TCPINTF_TO_PF_REQ = (IOT_TCPINTF_EVENT + 3)
IOT_TCPINTF_TO_PF_RSP = (IOT_TCPINTF_EVENT + 4)

# HTTPINTF
IOT_HTTPINTF_EVENT = (IOT_EVENT + 600)

IOT_PF_TO_HTTP_REQ = (IOT_HTTPINTF_EVENT + 1)
IOT_PF_TO_HTTP_RSP = (IOT_HTTPINTF_EVENT + 2)
IOT_HTTP_TO_PF_REQ = (IOT_HTTPINTF_EVENT + 3)
IOT_HTTP_TO_PF_RSP = (IOT_HTTPINTF_EVENT + 4)

# reader event
IOT_EVENT_READER = IOT_TCPINTF_TO_PF_REQ#(IOT_EVENT + 1)

# camera event
IOT_EVENT_CAMERA = IOT_TCPINTF_TO_PF_REQ#(IOT_EVENT + 2)

# 彩信发送
# Ennis modify at 2016-06-12 11:19, modify EVENT No for intfy_proxy
IOT_EVENT_MMS = IOT_TCPINTF_TO_PF_REQ #(IOT_EVENT + 7)